// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA60j-mJDWOT0HR83Avjv1LLhZzcC_vugA',
    appId: '1:698333827358:web:7196657286516d68f5390f',
    messagingSenderId: '698333827358',
    projectId: 'ecoop4-df108',
    authDomain: 'ecoop4-df108.firebaseapp.com',
    storageBucket: 'ecoop4-df108.appspot.com',
    measurementId: 'G-KVHBZCN9SN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDGVZlDiJrPUGT4GtEHLgUAV0F54YjHCUc',
    appId: '1:698333827358:android:0e41463db8013597f5390f',
    messagingSenderId: '698333827358',
    projectId: 'ecoop4-df108',
    storageBucket: 'ecoop4-df108.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBSvDHJ0EtmKAFhSJuPLi_8Wc253k-qPaU',
    appId: '1:698333827358:ios:4b84bfaac4b0f131f5390f',
    messagingSenderId: '698333827358',
    projectId: 'ecoop4-df108',
    storageBucket: 'ecoop4-df108.appspot.com',
    iosClientId: '698333827358-3pg3j0qnh3enm6pu0lq77srdt7uoka5k.apps.googleusercontent.com',
    iosBundleId: 'com.example.ecoop4',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBSvDHJ0EtmKAFhSJuPLi_8Wc253k-qPaU',
    appId: '1:698333827358:ios:4f5c247ac1c82c04f5390f',
    messagingSenderId: '698333827358',
    projectId: 'ecoop4-df108',
    storageBucket: 'ecoop4-df108.appspot.com',
    iosClientId: '698333827358-fpkdhnhgl4lm4b9esu8kc14hsml0566o.apps.googleusercontent.com',
    iosBundleId: 'com.example.ecoop4.RunnerTests',
  );
}
